---
site_name: Sicroc Docs
site_description: Documentation for Sicroc.
repo_url: https://github.com/jamesread/Sicroc
repo_name: jamesread/Sicroc
edit_uri: edit/main/docs
strict: true

markdown_extensions:
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

theme:
  name: material
  logo: logo.png
  favicon: logo.png
  language: en
  include_search_page: true
  search_index_only: true
  palette:
    primary: light green
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github


plugins:
  - social:
  - search:
  - tags:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jamesread/Sicroc

#    - icon: fontawesome/brands/bsky
#      link: https://bsky.app/profile/jamesread.bsky.social

    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@jamesread

    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/jamesreadtweets

nav:
  - Welcome: index.md
  
