---
name: "Build Tag"

on:
  push:
    tags:
      - '*'

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_TOKEN }}

      - name: make container-image-base
        run: make docker-container-image-base

      - name: make container-image
        run: make docker-container-image

      - name: docker tag
        run: docker tag localhost/sicroc/sicroc:latest ghcr.io/jamesread/sicroc:${{ github.ref_name }}

      - name: docker push
        run: docker push ghcr.io/jamesread/sicroc:${{ github.ref_name }}
